### ISSUE TITLE
::-moz-focus-inner no longer needed

### ISSUE THREAD

**Issue by jonathantneal** [henryruhs/harmonize.css#2]
The ::-moz-focus-inner and :-moz-focusring issues seem to have been fixed in Firefox 53. See https://bugzilla.mozilla.org/show_bug.cgi?id=140562

**Comment by henryruhs** [comment]
I cannot confirm that - the inner focus is still present - tested in Firefox 61:

![bildschirmfoto von 2018-08-26 12-37-14](https://user-images.githubusercontent.com/1835397/44627361-e62a7f00-a92c-11e8-9398-90f9e11d44f9.png)
