### ISSUE TITLE
Don’t unset font styles on code-formatted elements

### ISSUE THREAD

**Issue by jonathantneal** [henryruhs/harmonize.css#3]
If someone is deliberately preformatting text (using `<pre>`) or code (using `<code>`), it may be better not to unset this property. normalize.css and @csstools/normalize.css safely set it to the default monospace, while sanitize.css, modern-normalize, and bootstrap reboot set it to the best known default system font.

**Comment by henryruhs** [comment]
Well, most of them are using something like - it has zero effect from my point of view:

```
code,
pre
{
	font-family: monospace;
	font-size: 1em;
}
```

Therefore, I remove that one and keep the browser standards:

```
code,
pre
{
	font: inherit;
}
```
