### ISSUE TITLE
Consider height:auto with img { max-width: 100% }, expand to include video

### ISSUE THREAD

**Issue by jonathantneal** [henryruhs/harmonize.css#5]
1. It’s a popular choice to set max-width: 100% on images, but in order to prevent the images from appearing stretched, you’d also need to add `height: auto`. You can see this done in other opinionated resets/normalize libraries.

2. While setting a max width on one kind of media, consider doing the same for video and audio (to be applied when it has controls). This is also done in one of the standarize libraries.

**Comment by henryruhs** [comment]
Thank you for pointing this out! The `height: auto` is kind of a browser standard - so I don't think we need to set it...  `height: auto` overrides the `height` attribute as well and causes more issues.

I updated the rule to:

```
audio,
img,
video
{
	max-width: 100%;
}
```

At this point I cannot reproduce scaling issues using `max-width` - could you provide an example? If so we could use that one:

```
audio:not([width]),
img:not([width]),
video:not([width])
{
	max-width: 100%;
}
```

**Comment by henryruhs** [comment]
I reopen this issue as needed, okay?
